/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users": {
    get: operations["getUsers"];
    post: operations["createUser"];
    delete: operations["deleteUsers"];
    patch: operations["updateUsers"];
  };
}

export interface components {
  schemas: {
    User: {
      id: string;
      name: string;
      phoneNumber: string;
      age: number;
    };
    CreateUserBody: {
      name: string;
      phoneNumber: string;
      age: number;
    };
    UpdateUserBody: {
      name?: string;
      phoneNumber?: string;
      age?: number;
    };
  };
  responses: {
    /** Created */
    UsersAffected: {
      content: {
        "application/json": {
          usersAffected: number;
        };
      };
    };
    /** Returns the user */
    UserResponse: {
      content: {
        "application/json": components["schemas"]["User"];
      };
    };
    /** Returns the list of users */
    UsersResponse: {
      content: {
        "application/json": components["schemas"]["User"][];
      };
    };
  };
  parameters: {
    IdParam: string;
    PhoneNumberParam: string;
  };
  requestBodies: {
    CreateUserBody: {
      content: {
        "application/json": components["schemas"]["CreateUserBody"];
      };
    };
    UpdateUserBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserBody"];
      };
    };
  };
}

export interface operations {
  getUsers: {
    parameters: {
      query: {
        id?: components["parameters"]["IdParam"];
        phoneNumber?: components["parameters"]["PhoneNumberParam"];
      };
    };
    responses: {
      200: components["responses"]["UsersResponse"];
    };
  };
  createUser: {
    responses: {
      200: components["responses"]["UserResponse"];
    };
    requestBody: components["requestBodies"]["CreateUserBody"];
  };
  deleteUsers: {
    parameters: {
      query: {
        id?: components["parameters"]["IdParam"];
        phoneNumber?: components["parameters"]["PhoneNumberParam"];
      };
    };
    responses: {
      200: components["responses"]["UsersAffected"];
    };
  };
  updateUsers: {
    parameters: {
      query: {
        id?: components["parameters"]["IdParam"];
        phoneNumber?: components["parameters"]["PhoneNumberParam"];
      };
    };
    responses: {
      200: components["responses"]["UsersAffected"];
    };
    requestBody: components["requestBodies"]["UpdateUserBody"];
  };
}

export interface external {}
